version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    container_name: rails_app
    volumes:
      - '.:/rails'
    ports:
      - '3000:3000'
    environment:    
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:db/development.sqlite3
    depends_on:
      - stripe

  stripe:
    image: stripe/stripe-cli
    command: listen --forward-to http://app:3000/stripe/webhooks
    container_name: stripe_cli
    volumes:
      - stripe-cli-config:/root/.config/stripe

  test_app:
    build: .
    command: bundle exec rails spec
    container_name: test_rails_app
    volumes:
      - '.:/rails'
    environment:
      - DATABASE_URL=sqlite3:db/test.sqlite3
      - RAILS_ENV=test

volumes:
  db-data:
  stripe-cli-config:
